import * as T from './vendor/three.module.js';
import {Game} from './engine.mjs';
import {ArcadeMusic} from './audio.js';
const music=new ArcadeMusic();
const $=s=>document.querySelector(s),game=new Game(),view=$('#viewport');
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;view.prepend(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,100);const base=new T.Vector3(0,13.8,12.8);camera.position.copy(base);camera.lookAt(0,0,0);
scene.add(new T.HemisphereLight(0xc5e0ff,0x27204b,2.5));const light=new T.DirectionalLight(0xe0efff,3.3);light.position.set(-5,12,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-9,right:9,top:9,bottom:-9});light.shadow.bias=-.001;scene.add(light);const rim=new T.PointLight(0x6255ff,60,25);rim.position.set(4,4,-5);scene.add(rim);
const mat=(c,e=0)=>new T.MeshStandardMaterial({color:c,roughness:.42,metalness:.22,emissive:e,emissiveIntensity:.7});
const materials={floor:mat(0x24344a),wall:mat(0x4d6480),crate:mat(0xbf703f),trim:mat(0xf7b771),blue:mat(0x26b9eb),red:mat(0xff654c),dark:mat(0x111c2c),cyan:mat(0x8ef8ff,0x2bdcff),green:mat(0xbafa52,0x6ccf20),flame:mat(0xffd88a,0xff751c)};
function box(w,h,d,m,parent,x=0,y=0,z=0){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
const board=new T.Group();scene.add(board);box(11.35,.48,11.35,mat(0x111d35),board,0,-.4,0);box(11.4,.06,11.4,mat(0x6d76ff,0x4d40d8),board,0,-.56,0);
for(let z=0;z<11;z++)for(let x=0;x<11;x++)box(.96,.12,.96,materials.floor,board,x-5,-.09,z-5);
let walls=new T.Group(),actors=new T.Group(),fx=new T.Group();scene.add(walls,actors,fx);let gridStamp='',actorMeshes=new Map(),particles=[],shake=0,shakeOn=true;
function clear(group){while(group.children.length){const obj=group.children[0];group.remove(obj);obj.traverse(o=>o.geometry?.dispose());}}
function robot(color){let g=new T.Group();box(.53,.44,.42,color,g,0,.53);box(.62,.42,.48,color,g,0,.99);box(.5,.19,.035,materials.dark,g,0,1,.26);for(const x of [-.15,.15]){box(.09,.065,.04,materials.cyan,g,x,1.02,.29);box(.17,.24,.23,materials.dark,g,x,.19);box(.13,.3,.2,color,g,x*2.4,.56);}box(.06,.14,.06,materials.dark,g,0,1.28);box(.1,.07,.1,materials.cyan,g,0,1.37);return g;}
const exit=new T.Group();scene.add(exit);exit.position.set(4,.025,4);box(.8,.035,.8,materials.green,exit);box(.57,.045,.57,materials.dark,exit,0,.02);box(.28,.05,.28,materials.green,exit,0,.04);
function sync(){let stamp=game.grid.flat().join('');if(stamp!==gridStamp){gridStamp=stamp;clear(walls);for(let z=0;z<11;z++)for(let x=0;x<11;x++){const v=game.grid[z][x];if(!v)continue;let g=new T.Group();g.position.set(x-5,0,z-5);walls.add(g);if(v===1){box(.92,.85,.92,materials.wall,g,0,.42);box(.78,.035,.78,mat(0x637d96),g,0,.86);}else{box(.75,.7,.75,materials.crate,g,0,.36);for(let i of [-1,1]){box(.81,.09,.79,materials.trim,g,0,.36+i*.24);box(.08,.7,.79,materials.trim,g,i*.25,.36);}}}}
 const objects=[game.player,...game.enemies,...game.bombs];for(const [obj,mesh] of actorMeshes)if(!objects.includes(obj)){actors.remove(mesh);mesh.traverse(o=>o.geometry?.dispose());actorMeshes.delete(obj);}for(const obj of objects){let mesh=actorMeshes.get(obj);if(!mesh){if(obj===game.player||game.enemies.includes(obj))mesh=robot(obj===game.player?materials.blue:materials.red);else{mesh=new T.Group();const ball=new T.Mesh(new T.SphereGeometry(.3,18,14),materials.dark);ball.position.y=.34;ball.castShadow=true;mesh.add(ball);box(.07,.17,.07,materials.trim,mesh,0,.69);box(.1,.07,.1,materials.flame,mesh,0,.78);}mesh.position.set(obj.x-5,0,obj.z-5);actors.add(mesh);actorMeshes.set(obj,mesh);}mesh.position.x+=(obj.x-5-mesh.position.x)*.35;mesh.position.z+=(obj.z-5-mesh.position.z)*.35;if('t' in obj){let s=1+Math.sin(obj.t*30)*.09*(2-obj.t);mesh.scale.setScalar(s);mesh.children[0].material=obj.t<.65&&Math.sin(obj.t*35)>0?materials.red:materials.dark;}}
 clear(fx);for(const f of game.flames){box(.85,.2+f.t*.6,.85,materials.flame,fx,f.x-5,.2,f.z-5);}
 exit.children[0].material=game.enemies.length?materials.wall:materials.green;
 for(const event of game.events.splice(0)){music.effect(event.type);if(!['blast','crate','enemy'].includes(event.type))continue;if(event.type==='blast')shake=.18;for(let i=0;i<9;i++){let m=box(.11,.11,.11,event.type==='crate'?materials.trim:materials.flame,scene,event.x-5,.4,event.z-5);particles.push({m,t:.6,v:new T.Vector3((Math.random()-.5)*4,2+Math.random()*3,(Math.random()-.5)*4)});}}
 $('#time').textContent=`${Math.floor(Math.ceil(game.time)/60).toString().padStart(2,'0')}:${(Math.ceil(game.time)%60).toString().padStart(2,'0')}`;$('#score').textContent=String(game.score).padStart(5,'0');$('#enemies').innerHTML=`0${game.enemies.length} <span>/ 02</span>`;$('#status').textContent=game.state==='playing'?(game.enemies.length?'清除敌方机器人 · 注意躲避爆炸':'出口已开启 · 前往右下角'):({ready:'等待出发',paused:'已暂停',won:'挑战完成',lost:'挑战结束'}[game.state]);}
let previousState='';function ui(){if(game.state===previousState)return;previousState=game.state;music.update(game.state==='playing');if(game.state==='paused')music.stopEffects();if(game.state==='won'||game.state==='lost')music.effect(game.state);$('#overlay').hidden=game.state==='playing';$('#pause').textContent=game.state==='paused'?'▶ 继续':'Ⅱ 暂停';if(game.state==='ready')return;const data={paused:['TAKE A BREATHER','休息一下。','时间已冻结，准备好就继续。','继续挑战'],won:['ARENA CLEARED','漂亮，全场清空！',`最终得分 ${game.score} · 再来一局刷新纪录。`,'再玩一次'],lost:['ONE MORE TRY','差一点，再来！','给炸弹留两秒，给自己留条退路。','重新挑战']}[game.state];if(data){['#label','#title','#message','#start'].forEach((id,i)=>$(id).textContent=data[i]);}}
function start(){music.stopEffects();music.effect('start');if(game.state==='paused')game.state='playing';else{game.reset();game.state='playing';}keys.clear();sync();ui();}
function pause(){if(game.state==='playing')game.state='paused';else if(game.state==='paused')game.state='playing';keys.clear();ui();music.effect('click');}
$('#sound').onclick=()=>{const enabled=music.toggle();$('#sound').textContent=`♫ 声音 ${enabled?'ON':'OFF'}`;$('#sound').setAttribute('aria-pressed',String(enabled));if(enabled)music.effect('click');};
$('#start').onclick=start;$('#restart').onclick=start;$('#pause').onclick=pause;$('#shake').onclick=()=>{music.effect('click');shakeOn=!shakeOn;$('#shake').textContent=`震动 ${shakeOn?'ON':'OFF'}`;$('#shake').setAttribute('aria-pressed',String(shakeOn));};
const keys=new Set(),mapping={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};let moveClock=0;
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(mapping[k]||k===' ')e.preventDefault();if(e.repeat)return;if(k==='p'||k==='escape')pause();else if(k===' '){game.place();}else if(mapping[k]){keys.add(k);game.move(...mapping[k]);moveClock=.15;}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(game.state==='playing'){game.state='paused';ui();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='playing'){game.state='paused';ui();}});
function resize(){const {width,height}=view.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.fov=width<600?49:36;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(view);
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(game.state==='playing'){moveClock-=dt;if(moveClock<=0&&keys.size){game.move(...mapping[[...keys].at(-1)]);moveClock=.15;}game.tick(dt);for(const p of particles){p.t-=dt;p.v.y-=dt*9;p.m.position.addScaledVector(p.v,dt);p.m.rotation.x+=dt*4;}particles=particles.filter(p=>{if(p.t>0)return true;scene.remove(p.m);p.m.geometry.dispose();return false;});shake=Math.max(0,shake-dt);}sync();ui();camera.position.copy(base);if(shakeOn&&shake>0&&game.state==='playing'){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;}camera.lookAt(0,0,0);renderer.render(scene,camera);}resize();requestAnimationFrame(frame);
